services:
  - type: web
    name: eoddata-asx-live
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: EODDATA_API_KEY
        sync: false
